import Head from 'next/head'

import ConteudoCategoria from "@components/Conteudo/ConteudoCategoria"
import ConteudoInicio from "@components/Conteudo/ConteudoInicio"
import Menu from "@components/Menu"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      {/* <ConteudoInicio /> */}
      <ConteudoCategoria />
    </>
  )
}
